### ISSUE TITLE
Hiding active course hides active course class and not the course itself

### ISSUE THREAD

**Issue by asiom-tech** [asiom-tech-org/hoodle#3]
## Steps to reproduce:
1. Enter some course's page in Moodle (now it should be bold in Moodle's navigation menu)
2. Click edit courses list in Hoodle menu
3. Hide the current course
4. Enter another course's page
5. Now the active course is hidden, and not the previous course (the bold item is hidden, regardless of which course you're in)

## How to fix
This is happening due to the course id not appearing the same in the active course (under the `data-node-key` attribute), so the code considers it to be `null`.

Then in the storage we get `closed_null: true`, which shouldn't happen.

**Comment by ptechofficial** [comment]
Can i work on this?

**Comment by asiom-tech** [comment]
> Can i work on this?

@ptechofficial If you're a HUJI student then sure, otherwise I believe it's not possible (since you won't have access to this Moodle)
Thanks 😄

**Comment by ptechofficial** [comment]
> > Can i work on this?
> 
> @ptechofficial If you're a HUJI student then sure, otherwise I believe it's not possible (since you won't have access to this Moodle)
> Thanks 😄 

Oh right, sorry, I'm not a HUJI student. Anyway, thanks for the reply. :)
